Uses spawn for zipping instead of exec to prevent error
The error:
ERROR: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded